<?php
require_once __DIR__ . '/../config/config.php';
require_once __DIR__ . '/../includes/session.php';
require_once __DIR__ . '/../includes/commercial.php';
require_role('admin');

$q = db()->prepare('SELECT q.*, c.name AS cname FROM quotations q JOIN customers c ON c.id=q.customer_id WHERE q.id=?');
$q->execute([(int)$_GET['id']]);
$q = $q->fetch();
if (!$q) { set_flash('danger', 'Not found.'); header('Location: ' . base_url('quotations/index.php')); exit; }

$lines = db()->prepare('SELECT * FROM quotation_lines WHERE quotation_id=? ORDER BY sort_order')->execute([$q['id']])->fetchAll(PDO::FETCH_ASSOC);

header('Content-Type: text/html');
?>
<!DOCTYPE html><html><head><meta charset="utf-8"><title>Quotation <?= e($q['quotation_number']) ?></title>
<style>body{font-family:DejaVu Sans,Arial;font-size:12px;margin:20px;}table{width:100%;border-collapse:collapse;font-size:12px;}th,td{border:1px solid #ddd;padding:6px;}th{background:#eee;}.text-end{text-align:right;}.header{text-align:center;margin-bottom:20px;}.title{font-size:22px;}</style></head><body>
<div class="header"><div class="title">BrightBlaze Garage</div><div><strong>Quotation <?= e($q['quotation_number']) ?></strong></div></div>
<div style="margin-bottom:15px"><strong>Customer:</strong> <?= e($q['cname']) ?> | <strong>Date:</strong> <?= date('Y-m-d', strtotime($q['created_at'])) ?> | <strong>Status:</strong> <?= e($q['status']) ?></div>
<table><thead><tr><th>Description</th><th class="text-end">Qty</th><th class="text-end">Unit Price</th><th class="text-end">Total</th></tr></thead>
<tbody><?php foreach ($lines as $l): ?>
<tr><td><?= e($l['description']) ?></td><td class="text-end"><?= (float)$l['quantity'] ?></td><td class="text-end"><?= format_kwd($l['unit_price']) ?></td><td class="text-end"><?= format_kwd($l['line_total']) ?></td></tr>
<?php endforeach; ?>
<tr style="font-weight:bold"><td colspan="3" class="text-end">Total:</td><td class="text-end"><?= format_kwd($q['total']) ?></td></tr></tbody></table>
<p style="margin-top:30px;color:#999;font-size:10px">Generated by BrightBlaze Garage Management System</p></body></html>